FROM python:3.12-slim-bookworm

# RUN addgroup --gid 1000 flask
# RUN adduser --disabled-password --gecos "" --force-badname --ingroup 1000 docker

# USER docker
RUN mkdir /app

RUN chmod 777 /app

COPY requirements.txt /app/requirements.txt

# VOLUME ["/app"]

WORKDIR /app

# RUN python3 -m venv .venv
# RUN . .venv/bin/activate

RUN pip install -r requirements.txt

COPY app.py /app/app.py
COPY templates /app/templates

RUN flask db init
RUN flask db migrate
RUN flask db upgrade

VOLUME ["/app"]

EXPOSE 5000
# ENTRYPOINT ["flask"]
#CMD [ "flask", "run", "--host=0.0.0.0", "--port=5000"]
CMD ["tail", "-f", "/dev/null"]
