---
version: "3"
services:
  image-tag-gallery:
    image: draz1c/image-tag-gallery
    container_name: image-tag-gallery
    volumes:
      - './local-asset:/usr/src/app'
    user: docker
    restart: always
